plugin_repo(                                                                     
  name = "python",                                                               
  revision = "v1.2.0",                                                               
  plugin = "python-rules",                                                       
  owner = "please-build",                                                        
)