# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("HWord")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout.addWidget(self.searchButton, 1, 3, 1, 1)
        self.rb2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb2.setObjectName("rb2")
        self.gridLayout.addWidget(self.rb2, 2, 2, 1, 1)
        self.rb1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb1.setObjectName("rb1")
        self.gridLayout.addWidget(self.rb1, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 4)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.keywordLabel = QtWidgets.QLabel(self.centralwidget)
        self.keywordLabel.setObjectName("keywordLabel")
        self.gridLayout.addWidget(self.keywordLabel, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        self.gridLayout.addWidget(self.tableWidget, 4, 0, 1, 4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.fileTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileTypeLabel.setObjectName("fileTypeLabel")
        self.gridLayout.addWidget(self.fileTypeLabel, 2, 0, 1, 1)
        self.addDirButton = QtWidgets.QPushButton(self.centralwidget)
        self.addDirButton.setObjectName("addDirButton")
        self.gridLayout.addWidget(self.addDirButton, 0, 3, 1, 1)
        self.dstdirLabel = QtWidgets.QLabel(self.centralwidget)
        self.dstdirLabel.setObjectName("dstdirLabel")
        self.gridLayout.addWidget(self.dstdirLabel, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HWord"))
        self.searchButton.setText(_translate("MainWindow", "开始查询"))
        self.rb2.setText(_translate("MainWindow", "excel"))
        self.rb1.setText(_translate("MainWindow", "docx/doc"))
        self.keywordLabel.setText(_translate("MainWindow", "搜索关键字"))
        self.fileTypeLabel.setText(_translate("MainWindow", "文件类型"))
        self.addDirButton.setText(_translate("MainWindow", "添加文件夹"))
        self.dstdirLabel.setText(_translate("MainWindow", "指定检索目录"))
