# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 120, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        # self.rawLabel = QtWidgets.QLabel(Dialog)
        # self.rawLabel.setGeometry(QtCore.QRect(107, 30, 51, 31))
        # self.rawLabel.setObjectName("rawLabel")
        # self.rawValue = QtWidgets.QLineEdit(Dialog)
        # self.rawValue.setGeometry(QtCore.QRect(170, 29, 111, 31))
        # self.rawValue.setReadOnly(True)
        # self.rawValue.setObjectName("rawValue")
        self.newValue = QtWidgets.QLineEdit(Dialog)
        self.newValue.setGeometry(QtCore.QRect(170, 70, 111, 31))
        self.newValue.setObjectName("newValue")
        self.newLabel = QtWidgets.QLabel(Dialog)
        self.newLabel.setGeometry(QtCore.QRect(110, 70, 51, 31))
        self.newLabel.setObjectName("newLabel")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        # self.rawLabel.setText(_translate("Dialog", "原属性值"))
        self.newLabel.setText(_translate("Dialog", "修改为"))



class ModifyWindow(QtWidgets.QDialog, Ui_Dialog):
    # resultModifySignal = pyqtSignal(list)
    def __init__(self, mainw):
        super(ModifyWindow, self).__init__()
        self.setupUi(self)
        self.mainw = mainw


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = ModifyWindow('d')
    ui.show()
    sys.exit(app.exec_())
