# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filetool.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(566, 431)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dstdirLabel = QtWidgets.QLabel(Form)
        self.dstdirLabel.setObjectName("dstdirLabel")
        self.gridLayout.addWidget(self.dstdirLabel, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.addDirButton = QtWidgets.QPushButton(Form)
        self.addDirButton.setObjectName("addDirButton")
        self.gridLayout.addWidget(self.addDirButton, 0, 3, 1, 1)
        self.keywordLabel = QtWidgets.QLabel(Form)
        self.keywordLabel.setObjectName("keywordLabel")
        self.gridLayout.addWidget(self.keywordLabel, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.searchButton = QtWidgets.QPushButton(Form)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout.addWidget(self.searchButton, 1, 3, 1, 1)
        self.fileTypeLabel = QtWidgets.QLabel(Form)
        self.fileTypeLabel.setObjectName("fileTypeLabel")
        self.gridLayout.addWidget(self.fileTypeLabel, 2, 0, 1, 1)
        self.rb1 = QtWidgets.QRadioButton(Form)
        self.rb1.setObjectName("rb1")
        self.gridLayout.addWidget(self.rb1, 2, 1, 1, 1)
        self.rb2 = QtWidgets.QRadioButton(Form)
        self.rb2.setObjectName("rb2")
        self.gridLayout.addWidget(self.rb2, 2, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 4)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        self.gridLayout.addWidget(self.tableWidget, 4, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dstdirLabel.setText(_translate("Form", "指定检索目录"))
        self.addDirButton.setText(_translate("Form", "添加文件夹"))
        self.keywordLabel.setText(_translate("Form", "搜索关键字"))
        self.searchButton.setText(_translate("Form", "开始查询"))
        self.fileTypeLabel.setText(_translate("Form", "文件类型"))
        self.rb1.setText(_translate("Form", "docx/doc"))
        self.rb2.setText(_translate("Form", "excel"))
