
github_repo(
  name = "pleasings",
  repo = "thought-machine/pleasings",
  revision = "master",
)

github_repo(
    name = "pleasings2",
    repo = "sagikazarmark/mypleasings",
    revision = "master",
)