[tool.poetry]
name = "finish"
version = "0.1.0"
description = "python-proto-example"
authors = ["jonpan <1191243580@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
